x-base: &base
  env_file: .env
  volumes: &base-volumes
    - proton:/opt/proton
    - gamefiles:/opt/gamefiles
    - dotnet-cache:/opt/dotnet-cache
  restart: unless-stopped

services:
  normal:
    <<: *base
    image: ghcr.io/deadlock-api/deadlock-server-plugins/normal:latest
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
    environment:
      - SERVER_PORT=27015
      - DEADWORKS_ENV_PORT=27015
    volumes:
      - proton:/opt/proton
      - gamefiles:/opt/gamefiles
      - dotnet-cache:/opt/dotnet-cache
      - gamedata-normal:/home/steam/server
      - compatdata-normal:/home/steam/.steam/steam/steamapps/compatdata

  lock-timer:
    <<: *base
    image: ghcr.io/deadlock-api/deadlock-server-plugins/lock-timer:latest
    ports:
      - "27016:27016/udp"
      - "27016:27016/tcp"
    environment:
      - SERVER_PORT=27016
      - DEADWORKS_ENV_PORT=27016
    volumes:
      - proton:/opt/proton
      - gamefiles:/opt/gamefiles
      - dotnet-cache:/opt/dotnet-cache
      - gamedata-lock-timer:/home/steam/server
      - compatdata-lock-timer:/home/steam/.steam/steam/steamapps/compatdata

  deathmatch:
    <<: *base
    image: ghcr.io/deadlock-api/deadlock-server-plugins/deathmatch:latest
    ports:
      - "27017:27017/udp"
      - "27017:27017/tcp"
    environment:
      - SERVER_PORT=27017
      - DEADWORKS_ENV_PORT=27017
    volumes:
      - proton:/opt/proton
      - gamefiles:/opt/gamefiles
      - dotnet-cache:/opt/dotnet-cache
      - gamedata-deathmatch:/home/steam/server
      - compatdata-deathmatch:/home/steam/.steam/steam/steamapps/compatdata

  trooper-invasion:
    <<: *base
    image: ghcr.io/deadlock-api/deadlock-server-plugins/trooper-invasion:latest
    ports:
      - "27018:27018/udp"
      - "27018:27018/tcp"
    environment:
      - SERVER_PORT=27018
      - DEADWORKS_ENV_PORT=27018
    volumes:
      - proton:/opt/proton
      - gamefiles:/opt/gamefiles
      - dotnet-cache:/opt/dotnet-cache
      - gamedata-trooper-invasion:/home/steam/server
      - compatdata-trooper-invasion:/home/steam/.steam/steam/steamapps/compatdata

volumes:
  proton:
  gamefiles:
  gamedata-normal:
  gamedata-lock-timer:
  gamedata-deathmatch:
  gamedata-trooper-invasion:
  compatdata-normal:
  compatdata-lock-timer:
  compatdata-deathmatch:
  compatdata-trooper-invasion:
  dotnet-cache:
